In [35]:
data = 123

data

123

In [36]:
str(data)

'123'

In [37]:
my_list = [1,2,3]
len(my_list)

3

In [38]:
import numpy as np

data = [1,2,3,4,5]
data

[1, 2, 3, 4, 5]

In [39]:
data1 = [1,2,3,4,4,5,3]
data1

[1, 2, 3, 4, 4, 5, 3]

In [40]:
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 4, 5, 3])

In [41]:
arr1.shape

(7,)

In [42]:
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [43]:
arr2.shape

(5,)

In [44]:
arr2.dtype

dtype('int32')

In [45]:
arr3 = np.array(data1)
arr3

array([1, 2, 3, 4, 4, 5, 3])

In [46]:
arr3.shape

(7,)

In [47]:
arr3.dtype

dtype('int32')

In [49]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr4.shape

(3, 3)

In [51]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [54]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [55]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [57]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
arr1.shape

(2, 3)

In [59]:
arr2 = np.array([[10,11,12],[13,14,15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [60]:
arr2.shape

(2, 3)

In [61]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [62]:
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [63]:
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [64]:
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [65]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
arr1.shape

(2, 3)

In [67]:
arr3 = np.array([10,11,12])
arr3

array([10, 11, 12])

In [68]:
arr3.shape

(3,)

In [69]:
arr1 + arr3

array([[11, 13, 15],
       [14, 16, 18]])

In [70]:
arr1 * arr3

array([[10, 22, 36],
       [40, 55, 72]])

In [71]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [72]:
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [73]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
arr1[0]

0

In [75]:
arr1[3]

3

In [76]:
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [77]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr2 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]]
                )
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [80]:
arr2[0,0]

1

In [81]:
arr2[2,3]

12

In [82]:
arr2[:,3]

array([ 4,  8, 12])

In [83]:
arr2 > 7

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [85]:
arr2[arr2 > 7]

array([ 8,  9, 10, 11, 12])